package com.example.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "user_profiles")
data class UserProfile(
    @PrimaryKey val id: Int = 1, // Single profile record
    val name: String = "Candidate",
    val targetCompany: String = "Google",
    val targetRole: String = "Software Engineer",
    val experienceLevel: String = "Mid-Level",
    val difficulty: String = "Medium",
    val streak: Int = 1,
    val lastActiveTimestamp: Long = System.currentTimeMillis(),
    val totalInterviewsCount: Int = 0,
    val averageAtsScore: Int = 0,
    val estimatedReadiness: Int = 45 // Out of 100
)

@Entity(tableName = "interview_sessions")
data class InterviewSession(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val company: String,
    val role: String,
    val difficulty: String,
    val mode: String, // Technical, HR, Behavioral, etc.
    val overallScore: Int = 0,
    val strengths: String = "",
    val weaknesses: String = "",
    val generalFeedback: String = "",
    val missedConcepts: String = "", // Missed concepts compiled by AI
    val suggestedLearningPlan: String = "", // Detailed study roadmap compiled by AI
    val recruiterComments: String = "", // Recruiter final expert comments
    val timestamp: Long = System.currentTimeMillis(),
    val isCompleted: Boolean = false,
    val currentStage: String = "Greeting" // "Greeting", "Warm-up", "Technical", "Cross-questioning", "Scenario", "Behavioral", "HR", "Completed"
)

@Entity(tableName = "interview_questions")
data class InterviewQuestion(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val sessionId: Int,
    val questionText: String,
    val userResponse: String = "",
    val score: Int = 0, // Score out of 10
    val starFormatRating: String = "",
    val confidenceScore: Int = 0,
    val communicationScore: Int = 0,
    val grammarScore: Int = 0,
    val technicalAccuracyScore: Int = 0,
    val clarityScore: Int = 0,
    val problemSolvingScore: Int = 0,
    val depthOfKnowledgeScore: Int = 0,
    val starFeedback: String = "", // Detailed STAR breakdown
    val idealAnswer: String = "", // Ideal answer generated by Gemini
    val tips: String = "",
    val orderIndex: Int = 0,
    val stageName: String = "Technical" // Stage name for this question
)

@Entity(tableName = "resume_analyses")
data class ResumeAnalysis(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val fileName: String = "Resume.pdf",
    val resumeText: String,
    val atsScore: Int = 0,
    val suggestions: String = "",
    val missingSkills: String = "",
    val formattingFeedback: String = "",
    val grammarFeedback: String = "",
    val matchedKeywords: String = "",
    val proposedCertsAndRoadmap: String = "",
    val timestamp: Long = System.currentTimeMillis()
)
